name: flutter_tex
description: A Flutter Package to render Mathematics / Maths, Physics and Chemistry, Statistics / Stats Equations based on LaTeX with full HTML and JavaScript support.

version: 1.0.9
author: Shahzad Akram <shahxadakram@gmail.com>
homepage: https://github.com/shahxadakram/flutter_tex

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mime: ^0.9.6+2

  webview_flutter: 
    git:
      url: https://github.com/dotneet/plugins.git
      ref: "dotneet/webview"
      path: packages/webview_flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
  - packages/flutter_tex/MathJax/index.html

